import { Inter } from "next/font/google";
import "./globals.css";

// Components
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Capizip",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} pt-24`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
